-- Seed awal section berdasarkan landing page saat ini

insert into sections (section_key, section_name, section_type, sort_order, is_active) values ('home', 'Dr. Aminullah, S.Sos, M.AP', 'static_html', 1, true) on conflict (section_key) do update set section_name=excluded.section_name, sort_order=excluded.sort_order;
insert into sections (section_key, section_name, section_type, sort_order, is_active) values ('biography', 'Biografi', 'static_html', 2, true) on conflict (section_key) do update set section_name=excluded.section_name, sort_order=excluded.sort_order;
insert into sections (section_key, section_name, section_type, sort_order, is_active) values ('education', 'Riwayat Pendidikan', 'static_html', 3, true) on conflict (section_key) do update set section_name=excluded.section_name, sort_order=excluded.sort_order;
insert into sections (section_key, section_name, section_type, sort_order, is_active) values ('research', 'Area Penelitian', 'static_html', 4, true) on conflict (section_key) do update set section_name=excluded.section_name, sort_order=excluded.sort_order;
insert into sections (section_key, section_name, section_type, sort_order, is_active) values ('publications', 'Publikasi Ilmiah', 'static_html', 5, true) on conflict (section_key) do update set section_name=excluded.section_name, sort_order=excluded.sort_order;
insert into sections (section_key, section_name, section_type, sort_order, is_active) values ('awards', 'Prestasi & Penghargaan', 'static_html', 6, true) on conflict (section_key) do update set section_name=excluded.section_name, sort_order=excluded.sort_order;
insert into sections (section_key, section_name, section_type, sort_order, is_active) values ('teaching', 'Mata Kuliah Yang Diampu', 'static_html', 7, true) on conflict (section_key) do update set section_name=excluded.section_name, sort_order=excluded.sort_order;
insert into sections (section_key, section_name, section_type, sort_order, is_active) values ('gallery', 'Berita & Aktivitas Akademik', 'static_html', 8, true) on conflict (section_key) do update set section_name=excluded.section_name, sort_order=excluded.sort_order;
insert into sections (section_key, section_name, section_type, sort_order, is_active) values ('contact', 'Kontak', 'static_html', 9, true) on conflict (section_key) do update set section_name=excluded.section_name, sort_order=excluded.sort_order;

insert into seo_settings (page_key, meta_title, meta_description, canonical_url, og_title, og_description, og_image_url, schema_json) values ('home', 'Dr. Aminullah — Akademisi & Peneliti', 'Profil akademik Dr. Aminullah, S.Sos, M.AP, mencakup biografi, riwayat pendidikan, area penelitian, publikasi ilmiah, penghargaan, aktivitas akademik, dan kontak.', 'https://domain-anda.com/', 'Dr. Aminullah — Akademisi & Peneliti', 'Profil akademik, publikasi ilmiah, penelitian, penghargaan, dan aktivitas akademik Dr. Aminullah, S.Sos, M.AP.', 'assets/images/dr-aminullah-profile.jpg', '{"@context":"https://schema.org","@type":"Person","name":"Dr. Aminullah, S.Sos, M.AP"}'::jsonb) on conflict (page_key) do nothing;
